### PR TITLE
Edit Item Modal Completed

### PR DESCRIPTION
**Pull request by rishnarenikunta**
Finished the edit item modal and fixed z-index issues in add item

### CODE REVIEW

**Review by emoryjgrubbs — COMMENTED** [review]
functionality looks good

modal looks small

item name input should be left justified to be consistant
you should also use the input css class for text input + the headless ui list box for the category dropdown

i think the z value has affected the category drop down
image

**Comment by rishnarenikunta** [comment]
- fixed z index, but category dropdown overlap submit button but not for mobile (looked better as a scroll in mobile) 
- The API call works, besides the imageURL
- removed functionality of item count updating in add item
- Fixed pr reviews
Screenshot 2024-11-25 at 9 57 06 PM

**Comment by rishnarenikunta** [comment]
added the item.get.ts file that was previously deleted on accident

**Comment by emoryjgrubbs** [comment]
looks good, last couple things i see

add a divide-y to the listboxoptions
on mobile, the category select's shadow gets cut off
add a overscroll-contain to scrollable sections to prevent the user accidentally moving the page

**Comment by rishnarenikunta** [comment]
addressed these comments
except, for mobile the shadow will be cut off because of how overflow-auto is implemented. If I have time later, I will come back to this issue later

**Review by emoryjgrubbs — APPROVED** [review]
make sure to make an issue so the shadow thing is tracked
other than that, everything looks good, go ahead and merge

**Pull request merged**
